spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://zipkin-server:9411
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka